<<<<<<< HEAD
version: "3.8"

services:
    web:
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - db
      environment:
        DATABASE_URL: postgres://user:password@db/Users

    db:
      image: postgres:13
      environment:
        POSTGRES_DB: Users
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
      volumes:
        - db_data:/var/lib/postgresql/data

volumes:
  db_data:
=======
version: '3.8'
services:
     web:
       build: .
       ports:
         - "8000:8000"
       depends_on:
         - db
       environment:
         DATABASE_URL: postgres://user:password@db/Users

     db:
       image: postgres:13
       environment:
         POSTGRES_DB: Users
         POSTGRES_USER: air
         POSTGRES_PASSWORD: password
       volumes:
         - db_data:/var/lib/postgresql/data

volumes:
  db_data:
>>>>>>> origin/master
